version: "3.9"
services:
  server:           
    build:
      context: ./docker_sever
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/media0:/dev/media0"
    ports:
      - "8080:8080" 
    networks:
      network:
        ipv4_address: 172.18.0.2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
  redis:
    build:
        context: ./docker_redis
    stdin_open: true
    tty: true 
    ports:
      - "6379:6379"
    networks:
      network:
        ipv4_address: 172.18.0.3
    restart: always
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1